### ISSUE TITLE
[DEV] [FN] Test to create multisafe from UI

### ISSUE THREAD

**Issue by 4iresan** [multi-safe/ui.multisafe#3]
This ticket is to play around with UI interaction with creating multisafe, not from CLI bit from UI
Using dummy app we need to create a multisig with basic settings

- [x] dummy UI 'create new multisafe' #21
- [x] dummy UI with 'Add co-signer', no name is required, just address input #22
- [x] dummy UI with 'Amount of signers and signs required' #23
- [ ] after multisafe is created - redirect to dummy 'congrats' #24

**Acceptance criteria:**
- [x] As a logged in user I can trigger a multisafe creation
- [ ] I can add 2 co-signers
- [ ] My account is added automatically
- [x] I have a dropdown to select amount of signs required
- [x] After I click 'create' - I'm redirected to NEAR wallet
- [ ] After creation is successfull - I'm redirected to dummy 'congrats' (#24)
- [x] I can find my multisafe in NEAR browser
