### ISSUE TITLE
[DEV] Login options

### ISSUE THREAD

**Issue by 4iresan** [multi-safe/ui.multisafe#6]
A a user I want to see details of multisafe app.

- [x]  User can login via NEAR wallet #1
- [ ] User can login via Ledger #11
- [ ] User can go to read only mod #12
